# Generated by Django 5.0.6 on 2024-12-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_profile_pic_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
