# Generated by Django 5.0.6 on 2024-12-29 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_emergencycontact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('complaint_type', models.CharField(choices=[('domestic_violence', 'Domestic Violence'), ('harassment', 'Harassment'), ('assault', 'Assault'), ('cybercrime', 'Cybercrime'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='complaints/')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('judgment_status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
