# Generated by Django 5.0.6 on 2024-12-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='judgment_status',
            field=models.BooleanField(default=False),
        ),
    ]
