# Generated by Django 5.0.6 on 2024-12-29 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_complaint_judgment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='complaints/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_status', to='home.complaint')),
            ],
        ),
    ]
