# Generated by Django 5.0.6 on 2024-12-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_complaintstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintstatus',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
